[phases.setup]
nixPkgs = ['php82', 'composer', 'sqlite']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
    'touch database/database.sqlite',
    'chmod 664 database/database.sqlite',
    'chmod -R 775 storage',
    'chmod -R 775 bootstrap/cache'
]

[start]
cmd = 'php server.php' 