[phases.setup]
nixPkgs = ["php82", "php82Extensions.sqlite", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "chmod +x deploy-railway.sh",
  "./deploy-railway.sh"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT" 