[phases.setup]
nixPkgs = ["php82", "php82Extensions.sqlite"]

[phases.install]
cmds = [
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "chmod +x deploy-railway.sh",
  "./deploy-railway.sh"
]

[start]
cmd = "bash -c \"php artisan serve --host=0.0.0.0 --port=\\\$PORT\"" 